apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone-pipeline
spec:
  description: >-
    A pipeline to clone from a private GitHub repo
  params:
    - name: github-repo-url
      description: The private GitHub Repo
    - name: github-repo-revision
      description: The GitHub revision to use
      default: master
  workspaces:
    - name: source
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.github-repo-url)
        - name: revision
          value: $(params.github-repo-revision)
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: source
    - name: build-dotnet-app
      taskRef:
        name: dotnet-build
      runAfter: 
        - clone-source
      workspaces:
        - name: directory
          workspace: source
